name: Build & Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Builder npm install, build
        working-directory: ./builder
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
      - name: Builder-test npm install
        working-directory: ./builder
        run: npm install
        env:
          CI: true
      - name: Builder test
        working-directory: ./builder
        run: npm test
        env:
          CI: true
