name: ngx-aws-deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Clone repository
        # `fetch-depth` defaults to 1.
        uses: actions/checkout@v2
      - name: Cache builder node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-${{ matrix.version }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - name: Install Builder Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Symlink dist 🔗
        run: npm run symlinks        
      - name: Tests coverage
        run: npm run nx run-many -- --target=test --all --codeCoverage
      - name: Build
        run: npm run nx run-many -- --target=build --all --parallel=true --with-deps=true --prod
